Tablero varios componentes y estrucura
UNIZAR-30226-2021-07/app pull request #117
Opened 2021-04-30 13:14 UTC by Leticia-23

Closes #91 
Closes #92 
Closes #94 
Closes #93

2021-05-02 00:29 UTC, xzebra requested changes
Hola, no se si es por la integración en la pantalla de tablero o por mi versión de flutter, pero la "animación" de arrastrar una carta no está funcionando igual que en la pantalla de reglas. La carta desaparece mientras está siendo arrastrada.

2021-05-02 00:30 UTC, xzebra commented
Creo que se puede deber a alguno de estos errores que saltan cuando muevo una carta.
```
Another exception was thrown: BoxConstraints forces an infinite height.

Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#31239 relayoutBoundary=up2
NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#b4e67 relayoutBoundary=up1
NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#b4e67 relayoutBoundary=up1

Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1711 pos
12: '!_debugDoingThisLayout': is not true.
```

2021-05-02 09:23 UTC, Leticia-23 commented
Era por la integración, una de las medidas que utilicé para encajar los componentes, así que no problem con tu versión. 
En principio ya está solucionado.

2021-05-03 10:29 UTC, Tomenos18 approved these changes

2021-05-03 10:31 UTC, Tomenos18 approved these changes

2021-05-03 10:37 UTC, xzebra approved these changes

2021-05-03 10:37 UTC, xzebra commented
Vale ya funciona correctamente

2021-05-03 10:37 UTC, merged