Ultimo pr
UNIZAR-30226-2021-07/app pull request #154
Opened 2021-05-22 15:34 UTC by Tomenos18

Closes #152 

Funcional lo de que salga que se a acabado la partida

2021-05-22 17:47 UTC, marioortizmanero commented
no es el ultimo porque te falta el timer crack

2021-05-22 17:54 UTC, Tomenos18 commented
> no es el ultimo porque te falta el timer crack

Lee la descripción pero con (crono = timer)

2021-05-22 18:05 UTC, marioortizmanero commented
vamooooooooos eres un grande

2021-05-22 18:05 UTC, marioortizmanero approved these changes
un grande

2021-05-23 16:35 UTC, xzebra requested changes
![image](https://user-images.githubusercontent.com/20362769/119268971-9704fc00-bbf5-11eb-9e5c-0f9a1189baa2.png)
El timer se queda con tiempo maximo con el que te has reconectado.

2021-05-23 16:49 UTC, xzebra approved these changes

2021-05-23 16:49 UTC, merged