Añadidos módulos y navegaciones - faltan navegaciones por configurar
UNIZAR-30226-2021-07/app pull request #51
Opened 2021-03-31 20:46 UTC by Leticia-23

2021-04-01 11:37 UTC, xzebra requested changes
- [ ] La pantalla de crear cuenta debería permitir volver a la de inicio de sesión por si se le ha dado sin querer.
- [ ] El botón de atrás del móvil en perfil cierra la aplicación.
- [ ] El botón de atrás del móvil cierra el popup de uniendose a partida.

2021-04-01 12:39 UTC, Tomenos18 commented
Romanos hazte pull que nada de eso pasa menos lo del pop-up, pero eso ya lo trabajaremos cuando hagamos el tablero

2021-04-01 12:40 UTC, Tomenos18 commented
Por mi todo ok

2021-04-01 12:41 UTC, Tomenos18 approved these changes

2021-04-01 13:55 UTC, Tomenos18 commented
Habria que cambiar varios push replazament por push normales

2021-04-02 17:30 UTC, Leticia-23 commented
- Para todos los popups: He dejado con bloqueo para que no se salga al pretar en otro sitio de la pantalla que no sea el popup
- Para los popUps de los códigos y empezar partida: he bloqueado el botón de back del móvil
- Para eliminar cuenta y el de error se sigue pudiendo salir del popup con botón back del móvil (ya que se da la opción en el propio popup)
- El de carga de partida pública, por el momento no le he puesto bloqueo con el botón de back del móvil para que ahora no se quede bloqueado al no entrar en la pantalla de tablero.

2021-04-02 20:09 UTC, xzebra approved these changes
Perfecto todo ahora

2021-04-02 20:09 UTC, merged