Sistema sesiones
UNIZAR-30226-2021-07/app pull request #56
Opened 2021-04-05 12:32 UTC by Leticia-23

2021-04-05 22:19 UTC, Leticia-23 commented
La dejo como ready for review pero te explico @xzebra 
- Está todo en principio funcional con vistas a que en backend de cambié los códigos de las respuestas. Está ya implementado para que funcione cuando lo cambieis, pero faltará probarlo. 
- Falta también implementar el landing, para ver si hay sesión iniciada e ir a una pantalla u otra, pero aún no sé muy bien cómo haré, ya que he probado una cosa y no funcionaba. 
Entonces te lo dejo para que puedas revisarlo, si te parece conveniente mergear (he visto que web estaba lo han mergeado y supongo que les faltará también las comprobaciones de los cambios en backend) y que esas cosas las haga con otras issues me dices, o por si ves algo que tenga que modificar antes de además hacer ese par de cosas.

2021-04-06 09:16 UTC, xzebra approved these changes
Apruebo los cambios y ya harás lo del landing en otra rama si quieres. Mergéala tú que así me aseguro de que lo has leído.

2021-04-06 09:16 UTC, xzebra commented on lib/autentificacion/login.dart
> +                                                          if( await _authService.login(_mail.text,_pwd.text)) {
Puedes hacer dos cosas para el landing:
- Guardar el estado de login en el auth service, para poder consultar globalmente si está loggeado y, en caso contrario, actualizarlo.
- Subir el estado hasta main.dart con algún callback o algo así. Será un poco más problemático de actualizar en caso de que no esté identificado.

2021-04-06 09:16 UTC, xzebra commented on lib/main.dart
>  checkIfAuthenticated() async {
Para el landing tienes que hacer que esta función devuelva true si está loggeado el usuario y false si no.

2021-04-06 09:16 UTC, xzebra commented on lib/services/auth.dart
> +    var response = await http.get(Uri.parse(request));
Estaría mejor usar una petición de tipo POST porque oculta un poco los parámetros.

2021-04-06 09:16 UTC, xzebra commented on lib/services/auth.dart
> +    String request  = "http://gatovid.herokuapp.com/data/login?$parameters";
Hacer un login con un HTTP en lugar de HTTPS es un gran fallo de seguridad, no se si tendrás que cambiar la librería a una de https.

2021-04-06 09:16 UTC, xzebra commented on lib/services/auth.dart
> +    String request  = "http://gatovid.herokuapp.com/data/login?$parameters";
cualquier persona con un inspeccionador de paquetes en tu misma red podría ver tu contraseña e email en texto plano

2021-04-06 09:16 UTC, xzebra commented on lib/services/auth.dart
> +      "Authorization" : "Bearer $token"
Recomiendo hacer un método genérico para las peticiones con y sin autenticación, porque sino vais a tener que repetir esto 80 veces.

2021-04-06 16:28 UTC, xzebra requested changes
Esperar a mergear hasta que se cambie a HTTPS

2021-04-06 22:43 UTC, Leticia-23 commented
Mergeada rama de registro y borrar cuentas para revisión conjunta con el resto de peticiones de cambios,
Closes #11 #59

2021-04-07 00:22 UTC, Leticia-23 commented
- He cambiado las request a https y post
- He hecho el método ```requestToken()``` No he hecho nada más, así cuando se junte con lo de Tomás si vemos que renta hacer más métodos genéricos los haremos y sino pues así.
- El landing lo he intentado de un par de maneras pero no consigo, lo dejo comentado, se podría hacer en otra branch y mergear esta ya si no hay problemas adicionales.

2021-04-07 12:34 UTC, Tomenos18 approved these changes

2021-04-07 13:02 UTC, xzebra approved these changes
Mergeo esto y dejo que hagais el landing y juntar todo en otras ramas

2021-04-07 13:03 UTC, merged