Varias cosas
UNIZAR-30226-2021-07/app pull request #73
Opened 2021-04-17 15:39 UTC by Tomenos18

Closes #70
Closes #72

Todo lo contenido en los issues 70 y 72

2021-04-17 20:20 UTC, Tomenos18 commented
Closes #62 

Para la persistencia de datos basta con guardarse el passwd y email, el resto de cosas se piden al servidor cada vez que inicias la aplicacion

2021-04-17 21:15 UTC, xzebra commented
> Para la persistencia de datos basta con guardarse el passwd y email, el resto de cosas se piden al servidor cada vez que inicias la aplicacion

Chavales por favor meditad medio segundo las cuestiones de seguridad que puede tener almacenar datos confidenciales como un correo o una contraseña. La mera existencia del token es para evitar que la contraseña esté almacenada en cualquier sitio y, por lo tanto, expuesta.

En caso de exponer el almacenamiento interno del dispositivo se podría desencriptar la contraseña y el email, que probablemente no sean únicos de esta aplicación, sino que el usuario los usaría en varias otras apps y servicio.

2021-04-17 21:20 UTC, xzebra commented
Para la persistencia de la sesión se debe almacenar el token el tiempo que dure dicha sesión, hasta que se reciba un error de no autenticado (si no recuerdo mal, código 401). En caso de no estar autenticado, se tiene que redirigir al usuario al login y que sea él quien manualmente inicie sesión; en el futuro se hará que el token dure más tiempo o se hará un sistema que autorefresque el token.

2021-04-17 21:24 UTC, xzebra requested changes
Bloqueo el merge hasta que se revise lo mencionado

2021-04-17 22:38 UTC, Tomenos18 commented
Revisado

2021-04-18 14:29 UTC, xzebra requested changes

2021-04-18 14:29 UTC, xzebra commented on lib/services/profile_stadistics.dart
> +    // TODO: Irse al login
Esto era para un futuro o para implementarlo en esta PR?

2021-04-18 14:46 UTC, Tomenos18 commented on lib/services/profile_stadistics.dart
> +    // TODO: Irse al login
comentario sin quitar

2021-04-18 14:48 UTC, Tomenos18 commented on lib/services/profile_stadistics.dart
> +    // TODO: Irse al login
quitado

2021-04-18 17:10 UTC, xzebra approved these changes
vale todo perfecto ahora

2021-04-18 17:10 UTC, merged